unbind r
bind r source-file ~/.tmux.conf

# set -g default-terminal "tmux-256color"
# set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-s
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g mode-keys vi

bind -r m resize-pane -Z
bind -r h resize-pane -L 5  # Resize left
bind -r l resize-pane -R 5  # Resize right
bind -r k resize-pane -U 5  # Resize up
bind -r j resize-pane -D 5  # Resize down

# Tokyo Night Moon Colors
set -g status-bg "#1a1b26"   # Background
set -g status-fg "#c0caf5"   # Foreground

# Left side of the status bar
set -g status-left "#[bg=#7aa2f7,fg=#1a1b26] ❖ #[bg=#1a1b26,fg=#c0caf5] #S "

# Right side of the status bar
set -g status-right "#[bg=#1a1b26,fg=#bb9af7] %Y-%m-%d #[fg=#9ece6a] %H:%M "

# Active and Inactive Window Styles
set -g window-status-current-format "#[bg=#7aa2f7,fg=#1a1b26] #I:#W #[bg=#1a1b26,fg=#c0caf5]"
set -g window-status-format "#[fg=#565f89] #I:#W "

# Pane Border Styles
set -g pane-border-fg "#3b4261"
set -g pane-active-border-fg "#7aa2f7"

# set-option -g status-position top
set -g status-left ''
set -g status-right ''
set -g status-right '#{pane_current_path}'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
set -g @theme_variation 'moon'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Bind Alt+F to toggle fullscreen for the current pane
bind -n M-f resize-pane -Z

# Bind Alt+X to kill the current pane
bind -n M-x kill-pane

run '~/.tmux/plugins/tpm/tpm'
