############################################## backend
animations = ({
    triggers = ["open", "show"];
    preset = "appear";
    duration = 0.1;
    scale = 0.9;
},{
    triggers = ["close", "hide"];
    preset = "disappear";
    duration = 0.1;
    scale = 0.9;
},{
    triggers = ["geometry"];
    preset = "geometry-change";
    duration = 0.2;
});

backend = "glx";


# vsync
vsync = true;

# shadows
shadow = true;
no-dnd-shadow = true;
no-dock-shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.3;

# opacity
inactive-opacity = 0.55;
active-opacity = 0.85;

# fading
fading = true;
fade-delta = 7;
fade-in-step = 0.03;
fade-out-step = 0.14;

# blur
blur-method = "dual_kawase";
blur-strength = 8;
blur_background_frame = true;

# other
detect-client-opacity = true;
corner-radius = 10;

rounded-corners-exclude = [
#  "class_g = 'xfce4-panel'"
   "class_g = 'polybar'"
];  
# exclude certain apps from blur
blur-background-exclude = [
  "class_g = 'xfce4-panel'",
  "class_g = 'polybar'",
  "role = 'xborder'",
  # "class_g = 'Alacritty'"
];

# opacity exceptions
opacity-rule = [ 
  "100:class_g = 'xfce4-screenshooter'",
  "100:class_g = 'Google-chrome'",
  "95:class_g = 'zen-alpha'",
  "100:class_g = 'xviewer'",
  "95:class_g = 'code'",
  "95:class_g = 'steam'",
  "100:class_g = 'polybar'"
];

shadow-exclude = [
  "class_g = 'i3-frame'",
  "class_g = 'zen-alpha'",
  "class_g = 'xfce4-panel'",
  "class_g = 'xfce4-screenshooter'",
  "class_g = 'polybar'"
];

# disable opacity for borders
border-opacity = 1.0;
