import = ["~/.config/alacritty/tokyo-night-storm.toml"]
# Font configuration

[font]
size = 9.0

[env]
TERM = "alacritty"

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "Fira Code"
style = "Regular"

[window]
opacity = 0
